export enum ETypeContext {
  "一般" = "base",
  "火" = "fire",
  "水" = "water",
  "格斗" = "fighting",
  "飞行" = "flying",
  "毒" = "poison",
  "地面" = "ground",
  "岩石" = "rock",
  "虫" = "bug",
  "幽灵" = "ghost",
  "钢" = "steel",
  "草" = "grass",
  "电" = "electric",
  "超能力" = "psychic",
  "冰" = "ice",
  "龙" = "dragon",
  "恶" = "dark",
  "妖精" = "fairy",
}
export enum ETypeColor {
  base = "#9FA19F",
  fire = "#D84816",
  water = "#2980EF",
  fighting = "#FF8000",
  flying = "#81B9EF",
  poison = "#9141CB",
  ground = "#915121",
  rock = "#AFA981",
  bug = "#91A119",
  ghost = "#704170",
  steel = "#60A1B8",
  grass = "#3FA129",
  electric = "#FAC000",
  psychic = "#EF4179",
  ice = "#3FD8FF",
  dragon = "#5060E1",
  dark = "#50413F",
  fairy = "#EF70EF",
}

export const areaNameList = [
  "關都",
  "城都",
  "豐緣",
  "神奧",
  "合眾",
  "卡洛斯",
  "阿羅拉",
  "伽勒爾",
  "洗翠",
  "帕底亞",
];

export enum EAreaName {
  "關都" = "kanto",
  "城都" = "johto",
  "豐緣" = "hoenn",
  "神奧" = "sinnoh",
  "合眾" = "unova",
  "卡洛斯" = "kalos",
  "阿羅拉" = "alola",
  "伽勒爾" = "galar",
  "洗翠" = "hisui",
  "帕底亞" = "paldea",
}
export const typeList = [
  "一般",
  "火",
  "水",
  "格斗",
  "飞行",
  "毒",
  "地面",
  "岩石",
  "虫",
  "幽灵",
  "钢",
  "草",
  "电",
  "超能力",
  "冰",
  "龙",
  "恶",
  "妖精",
];

export enum EPageName {
  "/pokemon/IllustratedBook" = "全國圖鑑",
  "/pokemon/MoveList" = "招式列表",
  "/pokemon/AreaList" = "地點列表",
}
