export enum ETypeContext {
  "一般" = "base",
  "火" = "fire",
  "水" = "water",
  "格斗" = "fighting",
  "飞行" = "flying",
  "毒" = "poison",
  "地面" = "ground",
  "岩石" = "rock",
  "虫" = "bug",
  "幽灵" = "ghost",
  "钢" = "steel",
  "草" = "grass",
  "电" = "electric",
  "超能力" = "psychic",
  "冰" = "ice",
  "龙" = "dragon",
  "恶" = "dark",
  "妖精" = "fairy",
}
export enum ETypeColor {
  base = "#9FA19F",
  fire = "#E62829",
  water = "#2980EF",
  fighting = "#FF8000",
  flying = "#81B9EF",
  poison = "#9141CB",
  ground = "#915121",
  rock = "#AFA981",
  bug = "#91A119",
  ghost = "#704170",
  steel = "#60A1B8",
  grass = "#3FA129",
  electric = "#FAC000",
  psychic = "#EF4179",
  ice = "#3FD8FF",
  dragon = "#5060E1",
  dark = "#50413F",
  fairy = "#EF70EF",
}

export const areaNameList = [
  "關都",
  "城都",
  "豐緣",
  "神奧",
  "合眾",
  "卡洛斯",
  "阿羅拉",
  "伽勒爾",
  "洗翠",
  "帕底亞",
];
